title: Alexander Schmidt # your name (or website title) here
logo: "/images/1740505134652.jpeg" # your photo (or logo) here
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: null # your Google Analytics tracking ID here
github:
  is_project_page: false
  is_user_page: false
  pdf_url: null
show_downloads: true
cv_url1: /pdf/Alexander_Schmidt_CV_EN.pdf
cv_url2: /pdf/Alexander_Schmidt_CV_EN_d.pdf
