title: Alexander Schmidt
logo: "/images/1740505134652.jpeg"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: none
gtm_container: GTM-WV38C3FT
github:
  is_project_page: false
  is_user_page: false
  pdf_url: null
show_downloads: true
cv_url1: /portfolio/pdf/Alexander_Schmidt_CV_EN.pdf
cv_url2: /portfolio/pdf/Alexander_Schmidt_CV_EN_d.pdf
